### ISSUE TITLE
Shade/play button don't change appearance on hover for secondary dashboards

### ISSUE THREAD

**Issue by TobiTenno** [WFCD/tennotv#33]
### Tenno.tv Issue
---

**Summary (short):**
When hovering on a video in `Categories`, for example, the play button doesn't get it's extra class, and the shade doesn't lose `hide`, but the next/previous buttons work. Suspect it's a bug switching tabs or something with show/hide.

---
**If issue, Reproduction:**
1. Load site
2. Click `Categories`
3. Hover over video

---
**Mockups, screenshots, evidence:**

![image](https://user-images.githubusercontent.com/7128721/50786050-07ef2780-1278-11e9-97af-138539c067b5.png)

---

**Additional context**

**Comment by Pckool** [comment]
Looking into it, here's what I found:
1. After clicking on categories, the spacing between the thumbnail spacing gets messed up again. This only happens because the divs with the class `.video` have a long width for some reason. My patch of #34 fixed the issue, but only on the first render.
2. After clicking on categories, any other page with a carousel of thumbnails gets the game bug. Meaning if you click on the creators tab again, the bug will still be present.
3. It seems that the app freezes up if you continuously switch between the tabs `Creators` and `Categories`

I'll edit this post as I discover more. I can probably patch the bug, I just need to keep digging.
